version: "3.1"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: test
      POSTGRES_DB: account
    ports:
      - "5432:5432"
